//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace GoWHMgmAdmin {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DataSetMonitor")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DataSetMonitor : global::System.Data.DataSet {
        
        private tblDeliveryOrderDataTable tabletblDeliveryOrder;
        
        private tblDeliveryDetailDataTable tabletblDeliveryDetail;
        
        private global::System.Data.DataRelation relationDeliveryOrderDetail;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DataSetMonitor() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DataSetMonitor(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["tblDeliveryOrder"] != null)) {
                    base.Tables.Add(new tblDeliveryOrderDataTable(ds.Tables["tblDeliveryOrder"]));
                }
                if ((ds.Tables["tblDeliveryDetail"] != null)) {
                    base.Tables.Add(new tblDeliveryDetailDataTable(ds.Tables["tblDeliveryDetail"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tblDeliveryOrderDataTable tblDeliveryOrder {
            get {
                return this.tabletblDeliveryOrder;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tblDeliveryDetailDataTable tblDeliveryDetail {
            get {
                return this.tabletblDeliveryDetail;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            DataSetMonitor cln = ((DataSetMonitor)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["tblDeliveryOrder"] != null)) {
                    base.Tables.Add(new tblDeliveryOrderDataTable(ds.Tables["tblDeliveryOrder"]));
                }
                if ((ds.Tables["tblDeliveryDetail"] != null)) {
                    base.Tables.Add(new tblDeliveryDetailDataTable(ds.Tables["tblDeliveryDetail"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tabletblDeliveryOrder = ((tblDeliveryOrderDataTable)(base.Tables["tblDeliveryOrder"]));
            if ((initTable == true)) {
                if ((this.tabletblDeliveryOrder != null)) {
                    this.tabletblDeliveryOrder.InitVars();
                }
            }
            this.tabletblDeliveryDetail = ((tblDeliveryDetailDataTable)(base.Tables["tblDeliveryDetail"]));
            if ((initTable == true)) {
                if ((this.tabletblDeliveryDetail != null)) {
                    this.tabletblDeliveryDetail.InitVars();
                }
            }
            this.relationDeliveryOrderDetail = this.Relations["DeliveryOrderDetail"];
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DataSetMonitor";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DataSetMonitor.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabletblDeliveryOrder = new tblDeliveryOrderDataTable();
            base.Tables.Add(this.tabletblDeliveryOrder);
            this.tabletblDeliveryDetail = new tblDeliveryDetailDataTable();
            base.Tables.Add(this.tabletblDeliveryDetail);
            this.relationDeliveryOrderDetail = new global::System.Data.DataRelation("DeliveryOrderDetail", new global::System.Data.DataColumn[] {
                        this.tabletblDeliveryOrder.OrderNoColumn}, new global::System.Data.DataColumn[] {
                        this.tabletblDeliveryDetail.IDColumn}, false);
            this.Relations.Add(this.relationDeliveryOrderDetail);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializetblDeliveryOrder() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializetblDeliveryDetail() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DataSetMonitor ds = new DataSetMonitor();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void tblDeliveryOrderRowChangeEventHandler(object sender, tblDeliveryOrderRowChangeEvent e);
        
        public delegate void tblDeliveryDetailRowChangeEventHandler(object sender, tblDeliveryDetailRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class tblDeliveryOrderDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnOrderNo;
            
            private global::System.Data.DataColumn columnCustomerCode;
            
            private global::System.Data.DataColumn columnCustomerName;
            
            private global::System.Data.DataColumn columnMyCount;
            
            private global::System.Data.DataColumn columnDiffItems;
            
            private global::System.Data.DataColumn columnDeliveryRoute;
            
            private global::System.Data.DataColumn columnSalesResponsable;
            
            private global::System.Data.DataColumn columnPOperator;
            
            private global::System.Data.DataColumn columnWareHouse;
            
            private global::System.Data.DataColumn columnOrderDate;
            
            private global::System.Data.DataColumn columnOrderStatus;
            
            private global::System.Data.DataColumn columnAvizNo;
            
            private global::System.Data.DataColumn columnInvoiceNo;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryOrderDataTable() {
                this.TableName = "tblDeliveryOrder";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tblDeliveryOrderDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected tblDeliveryOrderDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OrderNoColumn {
                get {
                    return this.columnOrderNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CustomerCodeColumn {
                get {
                    return this.columnCustomerCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CustomerNameColumn {
                get {
                    return this.columnCustomerName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MyCountColumn {
                get {
                    return this.columnMyCount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DiffItemsColumn {
                get {
                    return this.columnDiffItems;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DeliveryRouteColumn {
                get {
                    return this.columnDeliveryRoute;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SalesResponsableColumn {
                get {
                    return this.columnSalesResponsable;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn POperatorColumn {
                get {
                    return this.columnPOperator;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn WareHouseColumn {
                get {
                    return this.columnWareHouse;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OrderDateColumn {
                get {
                    return this.columnOrderDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OrderStatusColumn {
                get {
                    return this.columnOrderStatus;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AvizNoColumn {
                get {
                    return this.columnAvizNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn InvoiceNoColumn {
                get {
                    return this.columnInvoiceNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryOrderRow this[int index] {
                get {
                    return ((tblDeliveryOrderRow)(this.Rows[index]));
                }
            }
            
            public event tblDeliveryOrderRowChangeEventHandler tblDeliveryOrderRowChanging;
            
            public event tblDeliveryOrderRowChangeEventHandler tblDeliveryOrderRowChanged;
            
            public event tblDeliveryOrderRowChangeEventHandler tblDeliveryOrderRowDeleting;
            
            public event tblDeliveryOrderRowChangeEventHandler tblDeliveryOrderRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddtblDeliveryOrderRow(tblDeliveryOrderRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryOrderRow AddtblDeliveryOrderRow(string OrderNo, string CustomerCode, string CustomerName, string MyCount, string DiffItems, string DeliveryRoute, string SalesResponsable, string POperator, string WareHouse, string OrderDate, string OrderStatus, string AvizNo, string InvoiceNo) {
                tblDeliveryOrderRow rowtblDeliveryOrderRow = ((tblDeliveryOrderRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        OrderNo,
                        CustomerCode,
                        CustomerName,
                        MyCount,
                        DiffItems,
                        DeliveryRoute,
                        SalesResponsable,
                        POperator,
                        WareHouse,
                        OrderDate,
                        OrderStatus,
                        AvizNo,
                        InvoiceNo};
                rowtblDeliveryOrderRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowtblDeliveryOrderRow);
                return rowtblDeliveryOrderRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                tblDeliveryOrderDataTable cln = ((tblDeliveryOrderDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new tblDeliveryOrderDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnOrderNo = base.Columns["OrderNo"];
                this.columnCustomerCode = base.Columns["CustomerCode"];
                this.columnCustomerName = base.Columns["CustomerName"];
                this.columnMyCount = base.Columns["MyCount"];
                this.columnDiffItems = base.Columns["DiffItems"];
                this.columnDeliveryRoute = base.Columns["DeliveryRoute"];
                this.columnSalesResponsable = base.Columns["SalesResponsable"];
                this.columnPOperator = base.Columns["POperator"];
                this.columnWareHouse = base.Columns["WareHouse"];
                this.columnOrderDate = base.Columns["OrderDate"];
                this.columnOrderStatus = base.Columns["OrderStatus"];
                this.columnAvizNo = base.Columns["AvizNo"];
                this.columnInvoiceNo = base.Columns["InvoiceNo"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnOrderNo = new global::System.Data.DataColumn("OrderNo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrderNo);
                this.columnCustomerCode = new global::System.Data.DataColumn("CustomerCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCustomerCode);
                this.columnCustomerName = new global::System.Data.DataColumn("CustomerName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCustomerName);
                this.columnMyCount = new global::System.Data.DataColumn("MyCount", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMyCount);
                this.columnDiffItems = new global::System.Data.DataColumn("DiffItems", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDiffItems);
                this.columnDeliveryRoute = new global::System.Data.DataColumn("DeliveryRoute", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDeliveryRoute);
                this.columnSalesResponsable = new global::System.Data.DataColumn("SalesResponsable", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSalesResponsable);
                this.columnPOperator = new global::System.Data.DataColumn("POperator", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPOperator);
                this.columnWareHouse = new global::System.Data.DataColumn("WareHouse", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnWareHouse);
                this.columnOrderDate = new global::System.Data.DataColumn("OrderDate", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrderDate);
                this.columnOrderStatus = new global::System.Data.DataColumn("OrderStatus", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrderStatus);
                this.columnAvizNo = new global::System.Data.DataColumn("AvizNo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAvizNo);
                this.columnInvoiceNo = new global::System.Data.DataColumn("InvoiceNo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInvoiceNo);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryOrderRow NewtblDeliveryOrderRow() {
                return ((tblDeliveryOrderRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new tblDeliveryOrderRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(tblDeliveryOrderRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tblDeliveryOrderRowChanged != null)) {
                    this.tblDeliveryOrderRowChanged(this, new tblDeliveryOrderRowChangeEvent(((tblDeliveryOrderRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tblDeliveryOrderRowChanging != null)) {
                    this.tblDeliveryOrderRowChanging(this, new tblDeliveryOrderRowChangeEvent(((tblDeliveryOrderRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tblDeliveryOrderRowDeleted != null)) {
                    this.tblDeliveryOrderRowDeleted(this, new tblDeliveryOrderRowChangeEvent(((tblDeliveryOrderRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tblDeliveryOrderRowDeleting != null)) {
                    this.tblDeliveryOrderRowDeleting(this, new tblDeliveryOrderRowChangeEvent(((tblDeliveryOrderRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovetblDeliveryOrderRow(tblDeliveryOrderRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSetMonitor ds = new DataSetMonitor();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "tblDeliveryOrderDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class tblDeliveryDetailDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnID;
            
            private global::System.Data.DataColumn columnOrderLineNo;
            
            private global::System.Data.DataColumn columnArticleCode;
            
            private global::System.Data.DataColumn columnArticleDesc1;
            
            private global::System.Data.DataColumn columnOrderQty;
            
            private global::System.Data.DataColumn columnReservedQty;
            
            private global::System.Data.DataColumn columnDeliverQty;
            
            private global::System.Data.DataColumn columnRemainQty;
            
            private global::System.Data.DataColumn columnUnitCodeStock;
            
            private global::System.Data.DataColumn columnWHDel;
            
            private global::System.Data.DataColumn columnGoWHClass;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryDetailDataTable() {
                this.TableName = "tblDeliveryDetail";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tblDeliveryDetailDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected tblDeliveryDetailDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IDColumn {
                get {
                    return this.columnID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OrderLineNoColumn {
                get {
                    return this.columnOrderLineNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ArticleCodeColumn {
                get {
                    return this.columnArticleCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ArticleDesc1Column {
                get {
                    return this.columnArticleDesc1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OrderQtyColumn {
                get {
                    return this.columnOrderQty;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ReservedQtyColumn {
                get {
                    return this.columnReservedQty;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DeliverQtyColumn {
                get {
                    return this.columnDeliverQty;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RemainQtyColumn {
                get {
                    return this.columnRemainQty;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn UnitCodeStockColumn {
                get {
                    return this.columnUnitCodeStock;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn WHDelColumn {
                get {
                    return this.columnWHDel;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn GoWHClassColumn {
                get {
                    return this.columnGoWHClass;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryDetailRow this[int index] {
                get {
                    return ((tblDeliveryDetailRow)(this.Rows[index]));
                }
            }
            
            public event tblDeliveryDetailRowChangeEventHandler tblDeliveryDetailRowChanging;
            
            public event tblDeliveryDetailRowChangeEventHandler tblDeliveryDetailRowChanged;
            
            public event tblDeliveryDetailRowChangeEventHandler tblDeliveryDetailRowDeleting;
            
            public event tblDeliveryDetailRowChangeEventHandler tblDeliveryDetailRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddtblDeliveryDetailRow(tblDeliveryDetailRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryDetailRow AddtblDeliveryDetailRow(tblDeliveryOrderRow parenttblDeliveryOrderRowByDeliveryOrderDetail, string OrderLineNo, string ArticleCode, string ArticleDesc1, string OrderQty, string ReservedQty, string DeliverQty, string RemainQty, string UnitCodeStock, string WHDel, string GoWHClass) {
                tblDeliveryDetailRow rowtblDeliveryDetailRow = ((tblDeliveryDetailRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        null,
                        OrderLineNo,
                        ArticleCode,
                        ArticleDesc1,
                        OrderQty,
                        ReservedQty,
                        DeliverQty,
                        RemainQty,
                        UnitCodeStock,
                        WHDel,
                        GoWHClass};
                if ((parenttblDeliveryOrderRowByDeliveryOrderDetail != null)) {
                    columnValuesArray[0] = parenttblDeliveryOrderRowByDeliveryOrderDetail[0];
                }
                rowtblDeliveryDetailRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowtblDeliveryDetailRow);
                return rowtblDeliveryDetailRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                tblDeliveryDetailDataTable cln = ((tblDeliveryDetailDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new tblDeliveryDetailDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnID = base.Columns["ID"];
                this.columnOrderLineNo = base.Columns["OrderLineNo"];
                this.columnArticleCode = base.Columns["ArticleCode"];
                this.columnArticleDesc1 = base.Columns["ArticleDesc1"];
                this.columnOrderQty = base.Columns["OrderQty"];
                this.columnReservedQty = base.Columns["ReservedQty"];
                this.columnDeliverQty = base.Columns["DeliverQty"];
                this.columnRemainQty = base.Columns["RemainQty"];
                this.columnUnitCodeStock = base.Columns["UnitCodeStock"];
                this.columnWHDel = base.Columns["WHDel"];
                this.columnGoWHClass = base.Columns["GoWHClass"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnID = new global::System.Data.DataColumn("ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnID);
                this.columnOrderLineNo = new global::System.Data.DataColumn("OrderLineNo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrderLineNo);
                this.columnArticleCode = new global::System.Data.DataColumn("ArticleCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnArticleCode);
                this.columnArticleDesc1 = new global::System.Data.DataColumn("ArticleDesc1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnArticleDesc1);
                this.columnOrderQty = new global::System.Data.DataColumn("OrderQty", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrderQty);
                this.columnReservedQty = new global::System.Data.DataColumn("ReservedQty", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservedQty);
                this.columnDeliverQty = new global::System.Data.DataColumn("DeliverQty", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDeliverQty);
                this.columnRemainQty = new global::System.Data.DataColumn("RemainQty", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRemainQty);
                this.columnUnitCodeStock = new global::System.Data.DataColumn("UnitCodeStock", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUnitCodeStock);
                this.columnWHDel = new global::System.Data.DataColumn("WHDel", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnWHDel);
                this.columnGoWHClass = new global::System.Data.DataColumn("GoWHClass", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGoWHClass);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryDetailRow NewtblDeliveryDetailRow() {
                return ((tblDeliveryDetailRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new tblDeliveryDetailRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(tblDeliveryDetailRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tblDeliveryDetailRowChanged != null)) {
                    this.tblDeliveryDetailRowChanged(this, new tblDeliveryDetailRowChangeEvent(((tblDeliveryDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tblDeliveryDetailRowChanging != null)) {
                    this.tblDeliveryDetailRowChanging(this, new tblDeliveryDetailRowChangeEvent(((tblDeliveryDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tblDeliveryDetailRowDeleted != null)) {
                    this.tblDeliveryDetailRowDeleted(this, new tblDeliveryDetailRowChangeEvent(((tblDeliveryDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tblDeliveryDetailRowDeleting != null)) {
                    this.tblDeliveryDetailRowDeleting(this, new tblDeliveryDetailRowChangeEvent(((tblDeliveryDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovetblDeliveryDetailRow(tblDeliveryDetailRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSetMonitor ds = new DataSetMonitor();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "tblDeliveryDetailDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class tblDeliveryOrderRow : global::System.Data.DataRow {
            
            private tblDeliveryOrderDataTable tabletblDeliveryOrder;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tblDeliveryOrderRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabletblDeliveryOrder = ((tblDeliveryOrderDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string OrderNo {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryOrder.OrderNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OrderNo\' in table \'tblDeliveryOrder\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryOrder.OrderNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CustomerCode {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryOrder.CustomerCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CustomerCode\' in table \'tblDeliveryOrder\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryOrder.CustomerCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CustomerName {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryOrder.CustomerNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CustomerName\' in table \'tblDeliveryOrder\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryOrder.CustomerNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string MyCount {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryOrder.MyCountColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MyCount\' in table \'tblDeliveryOrder\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryOrder.MyCountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DiffItems {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryOrder.DiffItemsColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DiffItems\' in table \'tblDeliveryOrder\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryOrder.DiffItemsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DeliveryRoute {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryOrder.DeliveryRouteColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DeliveryRoute\' in table \'tblDeliveryOrder\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryOrder.DeliveryRouteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SalesResponsable {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryOrder.SalesResponsableColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SalesResponsable\' in table \'tblDeliveryOrder\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryOrder.SalesResponsableColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string POperator {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryOrder.POperatorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'POperator\' in table \'tblDeliveryOrder\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryOrder.POperatorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string WareHouse {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryOrder.WareHouseColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'WareHouse\' in table \'tblDeliveryOrder\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryOrder.WareHouseColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string OrderDate {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryOrder.OrderDateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OrderDate\' in table \'tblDeliveryOrder\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryOrder.OrderDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string OrderStatus {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryOrder.OrderStatusColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OrderStatus\' in table \'tblDeliveryOrder\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryOrder.OrderStatusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string AvizNo {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryOrder.AvizNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AvizNo\' in table \'tblDeliveryOrder\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryOrder.AvizNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string InvoiceNo {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryOrder.InvoiceNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'InvoiceNo\' in table \'tblDeliveryOrder\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryOrder.InvoiceNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOrderNoNull() {
                return this.IsNull(this.tabletblDeliveryOrder.OrderNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOrderNoNull() {
                this[this.tabletblDeliveryOrder.OrderNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCustomerCodeNull() {
                return this.IsNull(this.tabletblDeliveryOrder.CustomerCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCustomerCodeNull() {
                this[this.tabletblDeliveryOrder.CustomerCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCustomerNameNull() {
                return this.IsNull(this.tabletblDeliveryOrder.CustomerNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCustomerNameNull() {
                this[this.tabletblDeliveryOrder.CustomerNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMyCountNull() {
                return this.IsNull(this.tabletblDeliveryOrder.MyCountColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMyCountNull() {
                this[this.tabletblDeliveryOrder.MyCountColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDiffItemsNull() {
                return this.IsNull(this.tabletblDeliveryOrder.DiffItemsColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDiffItemsNull() {
                this[this.tabletblDeliveryOrder.DiffItemsColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDeliveryRouteNull() {
                return this.IsNull(this.tabletblDeliveryOrder.DeliveryRouteColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDeliveryRouteNull() {
                this[this.tabletblDeliveryOrder.DeliveryRouteColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSalesResponsableNull() {
                return this.IsNull(this.tabletblDeliveryOrder.SalesResponsableColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSalesResponsableNull() {
                this[this.tabletblDeliveryOrder.SalesResponsableColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPOperatorNull() {
                return this.IsNull(this.tabletblDeliveryOrder.POperatorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPOperatorNull() {
                this[this.tabletblDeliveryOrder.POperatorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsWareHouseNull() {
                return this.IsNull(this.tabletblDeliveryOrder.WareHouseColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetWareHouseNull() {
                this[this.tabletblDeliveryOrder.WareHouseColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOrderDateNull() {
                return this.IsNull(this.tabletblDeliveryOrder.OrderDateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOrderDateNull() {
                this[this.tabletblDeliveryOrder.OrderDateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOrderStatusNull() {
                return this.IsNull(this.tabletblDeliveryOrder.OrderStatusColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOrderStatusNull() {
                this[this.tabletblDeliveryOrder.OrderStatusColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAvizNoNull() {
                return this.IsNull(this.tabletblDeliveryOrder.AvizNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAvizNoNull() {
                this[this.tabletblDeliveryOrder.AvizNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsInvoiceNoNull() {
                return this.IsNull(this.tabletblDeliveryOrder.InvoiceNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetInvoiceNoNull() {
                this[this.tabletblDeliveryOrder.InvoiceNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryDetailRow[] GettblDeliveryDetailRows() {
                if ((this.Table.ChildRelations["DeliveryOrderDetail"] == null)) {
                    return new tblDeliveryDetailRow[0];
                }
                else {
                    return ((tblDeliveryDetailRow[])(base.GetChildRows(this.Table.ChildRelations["DeliveryOrderDetail"])));
                }
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class tblDeliveryDetailRow : global::System.Data.DataRow {
            
            private tblDeliveryDetailDataTable tabletblDeliveryDetail;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal tblDeliveryDetailRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabletblDeliveryDetail = ((tblDeliveryDetailDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ID {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryDetail.IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ID\' in table \'tblDeliveryDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryDetail.IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string OrderLineNo {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryDetail.OrderLineNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OrderLineNo\' in table \'tblDeliveryDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryDetail.OrderLineNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ArticleCode {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryDetail.ArticleCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ArticleCode\' in table \'tblDeliveryDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryDetail.ArticleCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ArticleDesc1 {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryDetail.ArticleDesc1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ArticleDesc1\' in table \'tblDeliveryDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryDetail.ArticleDesc1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string OrderQty {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryDetail.OrderQtyColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OrderQty\' in table \'tblDeliveryDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryDetail.OrderQtyColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ReservedQty {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryDetail.ReservedQtyColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ReservedQty\' in table \'tblDeliveryDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryDetail.ReservedQtyColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DeliverQty {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryDetail.DeliverQtyColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DeliverQty\' in table \'tblDeliveryDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryDetail.DeliverQtyColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RemainQty {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryDetail.RemainQtyColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RemainQty\' in table \'tblDeliveryDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryDetail.RemainQtyColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string UnitCodeStock {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryDetail.UnitCodeStockColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UnitCodeStock\' in table \'tblDeliveryDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryDetail.UnitCodeStockColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string WHDel {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryDetail.WHDelColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'WHDel\' in table \'tblDeliveryDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryDetail.WHDelColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string GoWHClass {
                get {
                    try {
                        return ((string)(this[this.tabletblDeliveryDetail.GoWHClassColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'GoWHClass\' in table \'tblDeliveryDetail\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblDeliveryDetail.GoWHClassColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryOrderRow tblDeliveryOrderRow {
                get {
                    return ((tblDeliveryOrderRow)(this.GetParentRow(this.Table.ParentRelations["DeliveryOrderDetail"])));
                }
                set {
                    this.SetParentRow(value, this.Table.ParentRelations["DeliveryOrderDetail"]);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIDNull() {
                return this.IsNull(this.tabletblDeliveryDetail.IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIDNull() {
                this[this.tabletblDeliveryDetail.IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOrderLineNoNull() {
                return this.IsNull(this.tabletblDeliveryDetail.OrderLineNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOrderLineNoNull() {
                this[this.tabletblDeliveryDetail.OrderLineNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsArticleCodeNull() {
                return this.IsNull(this.tabletblDeliveryDetail.ArticleCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetArticleCodeNull() {
                this[this.tabletblDeliveryDetail.ArticleCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsArticleDesc1Null() {
                return this.IsNull(this.tabletblDeliveryDetail.ArticleDesc1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetArticleDesc1Null() {
                this[this.tabletblDeliveryDetail.ArticleDesc1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOrderQtyNull() {
                return this.IsNull(this.tabletblDeliveryDetail.OrderQtyColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOrderQtyNull() {
                this[this.tabletblDeliveryDetail.OrderQtyColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsReservedQtyNull() {
                return this.IsNull(this.tabletblDeliveryDetail.ReservedQtyColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetReservedQtyNull() {
                this[this.tabletblDeliveryDetail.ReservedQtyColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDeliverQtyNull() {
                return this.IsNull(this.tabletblDeliveryDetail.DeliverQtyColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDeliverQtyNull() {
                this[this.tabletblDeliveryDetail.DeliverQtyColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRemainQtyNull() {
                return this.IsNull(this.tabletblDeliveryDetail.RemainQtyColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRemainQtyNull() {
                this[this.tabletblDeliveryDetail.RemainQtyColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsUnitCodeStockNull() {
                return this.IsNull(this.tabletblDeliveryDetail.UnitCodeStockColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetUnitCodeStockNull() {
                this[this.tabletblDeliveryDetail.UnitCodeStockColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsWHDelNull() {
                return this.IsNull(this.tabletblDeliveryDetail.WHDelColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetWHDelNull() {
                this[this.tabletblDeliveryDetail.WHDelColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsGoWHClassNull() {
                return this.IsNull(this.tabletblDeliveryDetail.GoWHClassColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetGoWHClassNull() {
                this[this.tabletblDeliveryDetail.GoWHClassColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class tblDeliveryOrderRowChangeEvent : global::System.EventArgs {
            
            private tblDeliveryOrderRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryOrderRowChangeEvent(tblDeliveryOrderRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryOrderRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class tblDeliveryDetailRowChangeEvent : global::System.EventArgs {
            
            private tblDeliveryDetailRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryDetailRowChangeEvent(tblDeliveryDetailRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public tblDeliveryDetailRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591